
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package uweb.language;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RTRUE = 27;
  public static final int IDENTIFICADOR = 80;
  public static final int RPARRAFO = 6;
  public static final int MCLICKBOTON = 52;
  public static final int MCREARIMAGEN = 32;
  public static final int RFALSE = 28;
  public static final int RCOLUMNAC = 17;
  public static final int MSETCONTENIDO = 44;
  public static final int MENORIGUALQUE = 70;
  public static final int NUMERAL = 55;
  public static final int PYCOMA = 62;
  public static final int RCOLUMNA = 18;
  public static final int RELSE = 30;
  public static final int RESPACIO = 13;
  public static final int MSETPATH = 36;
  public static final int CORCHETEC = 61;
  public static final int RIMAGEN = 9;
  public static final int CORCHETEA = 60;
  public static final int MSETANCHO = 37;
  public static final int MGETTEXTO = 51;
  public static final int SIGNOIGUAL = 74;
  public static final int RIF = 29;
  public static final int RID = 23;
  public static final int MCREARPARRAFO = 40;
  public static final int MSETBORDE = 48;
  public static final int MGETCONTENIDO = 42;
  public static final int NOT = 67;
  public static final int MGETPATH = 33;
  public static final int SIGNOMENOS = 76;
  public static final int DISTINTOQUE = 72;
  public static final int RHS = 14;
  public static final int RCABECERA = 3;
  public static final int MGETALINEACION = 41;
  public static final int MENORQUE = 68;
  public static final int MSETALINEACION = 43;
  public static final int RALINEACION = 16;
  public static final int RANCHO = 22;
  public static final int MSETALTO = 38;
  public static final int RSALTO = 7;
  public static final int SIGNOPOR = 77;
  public static final int RFILA = 19;
  public static final int RCOMPI = 2;
  public static final int RBORDE = 25;
  public static final int MCREARBOTON = 49;
  public static final int COMA = 64;
  public static final int ENTERO = 81;
  public static final int MAYORIGUALQUE = 71;
  public static final int RTITULO = 4;
  public static final int DECIMAL = 82;
  public static final int SIGNODIVIDIDO = 78;
  public static final int MGETALTO = 35;
  public static final int RBOTON = 12;
  public static final int RPATH = 20;
  public static final int ECHO = 26;
  public static final int MGETANCHO = 34;
  public static final int EOF = 0;
  public static final int PUNTO = 63;
  public static final int RCUERPO = 5;
  public static final int IGUALQUE = 73;
  public static final int RFONDO = 15;
  public static final int OR = 65;
  public static final int error = 1;
  public static final int MSETTEXTO = 50;
  public static final int MINSERTAR = 39;
  public static final int SIGNOMAS = 75;
  public static final int ENDHS = 53;
  public static final int MCREARTABLA = 47;
  public static final int MAYORQUE = 69;
  public static final int RALTO = 21;
  public static final int PARENTC = 59;
  public static final int PARENTA = 58;
  public static final int MREPETIR = 31;
  public static final int CADENA = 79;
  public static final int DOLAR = 54;
  public static final int RTABLA = 8;
  public static final int MCREARTEXTOB = 46;
  public static final int MCREARTEXTOA = 45;
  public static final int RTEXTOB = 11;
  public static final int RTEXTOA = 10;
  public static final int RTEXTO = 24;
  public static final int AND = 66;
  public static final int LLAVEC = 57;
  public static final int LLAVEA = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RCOMPI",
  "RCABECERA",
  "RTITULO",
  "RCUERPO",
  "RPARRAFO",
  "RSALTO",
  "RTABLA",
  "RIMAGEN",
  "RTEXTOA",
  "RTEXTOB",
  "RBOTON",
  "RESPACIO",
  "RHS",
  "RFONDO",
  "RALINEACION",
  "RCOLUMNAC",
  "RCOLUMNA",
  "RFILA",
  "RPATH",
  "RALTO",
  "RANCHO",
  "RID",
  "RTEXTO",
  "RBORDE",
  "ECHO",
  "RTRUE",
  "RFALSE",
  "RIF",
  "RELSE",
  "MREPETIR",
  "MCREARIMAGEN",
  "MGETPATH",
  "MGETANCHO",
  "MGETALTO",
  "MSETPATH",
  "MSETANCHO",
  "MSETALTO",
  "MINSERTAR",
  "MCREARPARRAFO",
  "MGETALINEACION",
  "MGETCONTENIDO",
  "MSETALINEACION",
  "MSETCONTENIDO",
  "MCREARTEXTOA",
  "MCREARTEXTOB",
  "MCREARTABLA",
  "MSETBORDE",
  "MCREARBOTON",
  "MSETTEXTO",
  "MGETTEXTO",
  "MCLICKBOTON",
  "ENDHS",
  "DOLAR",
  "NUMERAL",
  "LLAVEA",
  "LLAVEC",
  "PARENTA",
  "PARENTC",
  "CORCHETEA",
  "CORCHETEC",
  "PYCOMA",
  "PUNTO",
  "COMA",
  "OR",
  "AND",
  "NOT",
  "MENORQUE",
  "MAYORQUE",
  "MENORIGUALQUE",
  "MAYORIGUALQUE",
  "DISTINTOQUE",
  "IGUALQUE",
  "SIGNOIGUAL",
  "SIGNOMAS",
  "SIGNOMENOS",
  "SIGNOPOR",
  "SIGNODIVIDIDO",
  "CADENA",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL"
  };
}

